blank_issues_enabled: false
contact_links:
  - name: Missional Digerati
    url: https://missionaldigerati.org
    about: Our main website.
  - name: Contributing
    url: https://contribute.missionaldigerati.org
    about: Learn more about contributing to our open source projects.
